Repository hmcts/bar-api, pull requests merged in 2020-04, with the labels that each got.

#343 Prepare for AKS
  Dockerfile
  Jenkinsfile_CNP
  api/build.gradle
  build.gradle
  charts/bar-api/Chart.yaml
  charts/bar-api/requirements.yaml
  charts/bar-api/values.aat.template.yaml
  charts/bar-api/values.preview.template.yaml
  charts/bar-api/values.yaml
Labels: ns:bar, rel:bar-api-pr-343

#344 Terraform fixes
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:bar, rel:bar-api-pr-344

#350 added fix for nightly build
  audit.json
Labels: ns:bar, rel:bar-api-pr-350

#354 Bar 1079
  Jenkinsfile_nightly
Labels: ns:bar, rel:bar-api-pr-354
