Repository hmcts/bar-api, pull requests merged in 2020-02, with the labels that each got.

#328 Mutation tests
  Jenkinsfile_nightly
  audit.json
  dependency-check-suppressions.xml
  security.sh
Labels: ns:bar, rel:bar-api-pr-328

#310 Bar 825
  api/src/main/java/uk/gov/hmcts/bar/api/converters/PaymentInstructionsCsvConverter.java
  api/src/main/java/uk/gov/hmcts/bar/api/data/enums/PaymentStatusEnum.java
  api/src/main/java/uk/gov/hmcts/bar/api/data/model/BasePaymentInstruction.java
  api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstruction.java
  api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstructionReportLine.java
  api/src/main/java/uk/gov/hmcts/bar/api/data/repository/PaymentInstructionStatusRepository.java
  api/src/main/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionService.java
  api/src/main/java/uk/gov/hmcts/bar/api/integration/payhub/service/PayHubService.java
  api/src/main/resources/db/changelog/db.changelog-payment-instruction.yaml
  api/src/test/java/uk/gov/hmcts/bar/api/componenttests/PayhubIntegrationTest.java
  api/src/test/java/uk/gov/hmcts/bar/api/componenttests/PaymentInstructionCsvRetrieveTest.java
  api/src/test/java/uk/gov/hmcts/bar/api/componenttests/PaymentInstructionUserFilterTest.java
  api/src/test/java/uk/gov/hmcts/bar/api/componenttests/utils/DbTestUtil.java
  api/src/test/java/uk/gov/hmcts/bar/api/integration/payhub/service/PayHubServiceTest.java
  dependency-check-suppressions.xml
Labels: ns:bar, ns:bar-api-pr-310, rel:bar-api-pr-310

#329 update jenkins file for nightly build
  Jenkinsfile_nightly
Labels: ns:bar, rel:bar-api-pr-329

#330 update audit.json
  audit.json
Labels: ns:bar, rel:bar-api-pr-330

#300 [[AR]] - BAR-869 Code changes for reported tab count
  api/src/main/java/uk/gov/hmcts/bar/api/controllers/payment/PaymentInstructionController.java
  api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstructionUserStatsWithRole.java
  api/src/main/java/uk/gov/hmcts/bar/api/data/repository/PaymentInstructionStatusRepository.java
  api/src/main/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionService.java
  api/src/main/java/uk/gov/hmcts/bar/api/data/utils/Util.java
  api/src/test/java/uk/gov/hmcts/bar/api/componenttests/PostalOrderCrudComponentTest.java
Labels: ns:bar, ns:bar-api-pr-300, rel:bar-api-pr-300
