Repository hmcts/bar-api, pull requests merged in 2021-02, with the labels that each got.

#426 Bar API CVE fix
  build.gradle
  cve-resolution-strategy.gradle
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-426

#435 PAY-4085 : Nightly Build issue fix
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-435

#417 PAY-3979-DB-Upgrade : DB Upgrade from v9.6 to v11
  charts/bar-api/Chart.yaml
  charts/bar-api/values.yaml
  docker/database/Dockerfile
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:bar, prd:bar, rel:bar-api-pr-417
