Repository hmcts/bar-api, pull requests merged in 2021-07, with the labels that each got.

#482 nightly build issue fix
  security.sh
Labels: ns:bar, prd:bar, rel:bar-api-pr-482

#485 Update dependency-check-suppressions.xml
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-485

#487 Update cve-resolution-strategy.gradle
  cve-resolution-strategy.gradle
Labels: ns:bar, prd:bar, rel:bar-api-pr-487

#490 Modified Functional Tests
  api/src/functionalTest/java/uk/gove/hmcts/bar/functional/SendToPayhubTest.java
  cve-resolution-strategy.gradle
Labels: ns:bar, prd:bar, rel:bar-api-pr-490
