Repository hmcts/bar-api, pull requests merged in 2022-09, with the labels that each got.

#544 adding suppression for snakeyaml issue
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-544

#548 Extend cve suppressions
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-548

#547 added db config, added demo.tfvars file for demo
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:bar, prd:bar, no-changes, rel:bar-api-pr-547

#549 new snakeyaml cve
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-549
