Repository hmcts/bar-api, pull requests merged in 2022-11, with the labels that each got.

#552 added new version of tomcat embed core and websocket
  cve-resolution-strategy.gradle
Labels: ns:bar, prd:bar, rel:bar-api-pr-552

#553 upgrade snakeyaml
  cve-resolution-strategy.gradle
Labels: ns:bar, prd:bar, rel:bar-api-pr-553

#554 Sonar critical issues fixes
  api/src/main/java/uk/gov/hmcts/bar/api/converters/PaymentInstructionsCsvConverter.java
Labels: ns:bar, prd:bar, rel:bar-api-pr-554
