Repository hmcts/bar-api, pull requests merged in 2023-02, with the labels that each got.

#560 owasp dependency check version upgrade
  build.gradle
  cve-resolution-strategy.gradle
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-560

#562 cve-fix
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-562

#564 upgrading to newest minor version of jackson databind
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-564
