Repository hmcts/bar-api, pull requests merged in 2023-01, with the labels that each got.

#557 cve fix
  cve-resolution-strategy.gradle
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-557

#558 updated depracted after to afterAlways
  .DS_Store
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/bar-api/Chart.yaml
Labels: ns:bar, prd:bar, rel:bar-api-pr-558

#559 Upgraded Terraform version to 1.3.7
  infrastructure/.terraform-version
  infrastructure/versions.tf
Labels: ns:bar, prd:bar, no-changes, rel:bar-api-pr-559
