Repository hmcts/bar-api, pull requests merged in 2023-10, with the labels that each got.

#613 PAY-6614 suppress tomcat CVEs
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-613

#620 version update
  charts/bar-api/Chart.yaml
  charts/bar-api/values.yaml
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-620

#622 PAY-6576 Flexible DB Creation
  infrastructure/main.tf
  infrastructure/provider.tf
  infrastructure/variables.tf
Labels: ns:bar, prd:bar, add-or-update, rel:bar-api-pr-622

#623 PAY-6576 Flexible DB rename
  dependency-check-suppressions.xml
  infrastructure/main.tf
Labels: ns:bar, prd:bar, destroy, rel:bar-api-pr-623

#624 Pay 6637
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-624

#625 Pay 6637
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-625
