Repository hmcts/bar-api, pull requests merged in 2023-06, with the labels that each got.

#582 Updating renovate config
  .github/renovate.json
Labels: ns:bar, prd:bar, rel:bar-api-pr-582

#585 PAY-6040-CVE-fixes
  cve-resolution-strategy.gradle
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-585

#586 PAY-6040: Update version to gradle-git-properties.
  api/build.gradle
  api/src/main/resources/bootstrap.yaml
  build.gradle
  charts/bar-api/Chart.yaml
  charts/bar-api/values.yaml
Labels: ns:bar, prd:bar, rel:bar-api-pr-586

#588 Fix to master pipeline.
  api/build.gradle
  api/src/main/resources/application.properties
  api/src/test/java/uk/gov/hmcts/bar/api/controllers/errors/ControllerExceptionHandlerTest.java
  build.gradle
  cve-resolution-strategy.gradle
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-588

#589 PAY-6040: Add latest CVE suppresssion
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-589
