Repository hmcts/bar-api, pull requests merged in 2023-09, with the labels that each got.

#600 PAY-6510: Nightly build pipeline fixes
  audit.json
Labels: ns:bar, prd:bar, rel:bar-api-pr-600

#602 CVE-2023-41080 FIX master
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-602

#603 PAY-6539
  audit.json
Labels: ns:bar, prd:bar, rel:bar-api-pr-603

#604 rennovate fix
  .github/renovate.json
Labels: ns:bar, prd:bar, rel:bar-api-pr-604

#607 PAY-6577_CVE-2023-34047
  dependency-check-suppressions.xml
Labels: ns:bar, prd:bar, rel:bar-api-pr-607
