Repository hmcts/bar-api, pull requests merged in 2023-12, with the labels that each got.

#635 PAY-6746 logback
  cve-resolution-strategy.gradle
Labels: ns:bar, prd:bar, rel:bar-api-pr-635

#636 PAY-6659-decommission v11 db for Bar
  charts/bar-api/Chart.yaml
  charts/bar-api/values.yaml
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:bar, prd:bar, destroy, rel:bar-api-pr-636

#637 PAY-6659-decommission v11 db for Bar
  infrastructure/provider.tf
Labels: ns:bar, prd:bar, destroy, rel:bar-api-pr-637

#638 PAY-6659: Correct azurerm feature
  infrastructure/main.tf
  infrastructure/provider.tf
Labels: ns:bar, prd:bar, destroy, rel:bar-api-pr-638

#639 PAY-6756 owasp upgrade
  build.gradle
Labels: ns:bar, prd:bar, rel:bar-api-pr-639
